#!/bin/bash
#PBS -N trimmomatic
#PBS -l nodes=c004:ppn=32
workdir=/lomi_home/gaoyang/microplastic_test/bioplastic_PRJEB15404/metagenome_illumina/workdir

cd $workdir

source /lomi_home/gaoyang/miniconda/bin/activate argranker

#linkdata
ln /lomi_home/gaoyang/microplastic_test/bioplastic_PRJEB15404/metagenome_illumina/0_extra/* $workdir/qc_control && cd qc_control
#fqc
/lomi_home/gaoyang/miniconda/envs/argranker/bin/fastqc ./*fastq -t 2 -o $workdir/qc_control

#PairEnd
for filename in *.man_1.fastq
do
base=$(basename $filename .man_1.fastq)

reads_1=${base}.man_1.fastq
reads_2=${base}.man_2.fastq

python /lomi_home/gaoyang/miniconda/envs/argranker/share/trimmomatic//trimmomatic PE -threads 2 -phred33 ${reads_1} ${reads_2} ${base}_clean_1.fq ${base}_u1 ${base}_clean_2.fq ${base}_u2 \
ILLUMINACLIP:/lomi_home/gaoyang/miniconda/envs/argranker/share/trimmomatic/adapters/TruSeq3-PE.fa:2:40:15 \
LEADING:2 TRAILING:2 \
SLIDINGWINDOW:4:20 MINLEN:25
done




